### ISSUE TITLE
Accepting HMR

### ISSUE THREAD

**Issue by nddery** [skyrpex/vue-jsx-loader#1]
I've been trying to use this loader but without success (I know you mentioned it could contain bugs).

Should we accept the module before checking for hot data ([here](https://github.com/skyrpex/vue-jsx-loader/blob/master/src/index.js#L31)), much like `vue-loader` [does here](https://github.com/vuejs/vue-loader/blob/master/lib/loader.js#L303) ?

With that, the page does not reload every time, as we accept the update, but `vue-hot-reload-api` doesn't update the component either (the client does receive the updated component though). I've tried changing `api.rerender()` to `api.reload()` (as per vue-loader) but it still didn't do the trick.

**Comment by skyrpex** [comment]
Thanks for the MR, it worked :+1:
